config/routes.rb
RevisionIt::Application.routes.draw do
  post "github/import_all" => 'github#import_all', as: 'import'
  get "github/hook"
  get "github/" => 'github#index', as: 'github'
  resources :revisions
  get 'hash/:hash' => 'revisions#via_hash'

end

app/models/revision.rb
class Revision < ActiveRecord::Base
  def self.from_hash(hash)
    self.where("hash_code like ?", "#{hash}%").order(:updated_at).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/error_handle.rb
module ErrorHandle
  def error(text, status)
    respond_to do |format|
      format.html { render text: text, status: status }
      format.json { render json: { status: 'error', reason: text }}
    end
  end
end

app/controllers/github_controller.rb
require 'uri'
require 'github_api'

class GithubController < ApplicationController
  include ErrorHandle
  def index
  end

  def import_all
    url = URI.parse params[:url]

    if url.host == 'github.com' then
      if url.path =~ %r!\A/([^/]*)/([^/]*)! then
        user = $1
        repos = $2
        Github.repos.commits.all(user, repos).each do|commit|
          Revision.where(hash_code: commit.sha).first_or_create! do |rev|
            rev.url = commit.html_url
            rev.log = commit.commit.message
          end
        end
        respond_to do|format|
          format.html { redirect_to github_path, notice: 'ok' }
          format.json { render json: { status: 'ok' } }
        end
      else
        error 'not valid url', 400
      end
    else
      error 'not github url', 400
    end
  end

  def hook
  end
end

app/controllers/revisions_controller.rb
class RevisionsController < ApplicationController
  include ErrorHandle
  before_action :set_revision, only: [:show, :edit, :update, :destroy]

  # GET /revisions
  # GET /revisions.json
  def index
    @revisions = Revision.all
  end

  # GET /revisions/1
  # GET /revisions/1.json
  def show
  end

  # GET /revisions/new
  def new
    @revision = Revision.new
  end

  # GET /revisions/1/edit
  def edit
  end

  # POST /revisions
  # POST /revisions.json
  def create
    @revision = Revision.new(revision_params)

    respond_to do |format|
      if @revision.save
        format.html { redirect_to @revision, notice: 'Revision was successfully created.' }
        format.json { render action: 'show', status: :created, location: @revision }
      else
        format.html { render action: 'new' }
        format.json { render json: @revision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /revisions/1
  # PATCH/PUT /revisions/1.json
  def update
    respond_to do |format|
      if @revision.update(revision_params)
        format.html { redirect_to @revision, notice: 'Revision was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @revision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /revisions/1
  # DELETE /revisions/1.json
  def destroy
    @revision.destroy
    respond_to do |format|
      format.html { redirect_to revisions_url }
      format.json { head :no_content }
    end
  end

  def via_hash
    if params[:hash].size < 4 then
      error 'ambiguous hash', 400
    else
      @revision = Revision.from_hash(params[:hash])
      if @revision then
        respond_to do |format|
          format.html { render 'embed', layout: false }
          format.json { render json: { status: 'ok', revision: @revision } }
        end
      else
        error 'No such revision', 404
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_revision
      @revision = Revision.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def revision_params
      params.require(:revision).permit(:hash_code, :url, :log)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/github_helper.rb
module GithubHelper
end

app/helpers/revisions_helper.rb
module RevisionsHelper
end

app/views/github/hook.html.haml
%h1 Github#hook
%p Find me in app/views/github/hook.html.haml

app/views/github/index.html.haml
%h2 Import revisions from github
= form_tag(import_path, method: "post") do
  .input-append
    %input.span4(type="text" placeholder="(e.g. http://github.com/codefirst/revision-it)" name="url")
    %button.btn Import

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "RevisionIt"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href='/') RevisionIt
          .container.nav-collapse
            %ul.nav
              %li= link_to "Import", github_path
              %li= link_to "Manage", revisions_path
              %li= link_to "About", "/path3"

    .container

      .row
        .span12
          = bootstrap_flash
          = yield

      %footer
        %p &copy; <a href="http://codefirst.org">Codefirst</a> 2014

app/views/revisions/_form.html.haml
= form_for @revision do |f|
  - if @revision.errors.any?
    #error_explanation
      %h2= "#{pluralize(@revision.errors.count, "error")} prohibited this revision from being saved:"
      %ul
        - @revision.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :hash_code
    = f.text_field :hash_code
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :log
    = f.text_area :log
  .actions
    = f.submit 'Save'

app/views/revisions/edit.html.haml
%h1 Editing revision

= render 'form'

= link_to 'Show', @revision
\|
= link_to 'Back', revisions_path

app/views/revisions/embed.html.haml
.revision-it-container(style="border-radius: 5px 5px 5px 5px; box-shadow: 1px 1px 2px #999999; padding: 10px;")
  .revision=link_to "#{@revision.hash_code[0,8]} #{@revision.log.each_line.first}", @revision.url
  .log(style="margin-left:10px")!=@revision.log.each_line.map(&method(:h)).to_a[1..-1].join("<br />")

app/views/revisions/index.html.haml
%h1 Listing revisions

%table
  %tr
    %th Hash code
    %th Url
    %th Log
    %th
    %th
    %th

  - @revisions.each do |revision|
    %tr
      %td= revision.hash_code
      %td= revision.url
      %td= revision.log
      %td= link_to 'Show', revision
      %td= link_to 'Edit', edit_revision_path(revision)
      %td= link_to 'Destroy', revision, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Revision', new_revision_path

app/views/revisions/new.html.haml
%h1 New revision

= render 'form'

= link_to 'Back', revisions_path

app/views/revisions/show.html.haml
%p#notice= notice

%p
  %b Hash code:
  = @revision.hash_code
%p
  %b Url:
  = @revision.url
%p
  %b Log:
  = @revision.log

= link_to 'Edit', edit_revision_path(@revision)
\|
= link_to 'Back', revisions_path